"""Added unique_columns column to remove_duplicates2 and highlight_duplicates2 table

Revision ID: 125fd5ad4048
Revises: 587acede6aef
Create Date: 2022-08-03 11:19:08.881039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '125fd5ad4048'
down_revision = '587acede6aef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('highlight_duplicates2', sa.Column('unique_columns', sa.String(), nullable=False))
    op.add_column('remove_duplicates2', sa.Column('unique_columns', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('remove_duplicates2', 'unique_columns')
    op.drop_column('highlight_duplicates2', 'unique_columns')
    # ### end Alembic commands ###
