"""updated server_default of status column of files table

Revision ID: 34d4c273c2c2
Revises: f364befd5582
Create Date: 2022-08-03 08:31:21.531758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34d4c273c2c2'
down_revision = 'f364befd5582'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
