"""added files, diff_checker, highlight_duplicates2 and remove_duplicates2 tables

Revision ID: 528666218b3a
Revises: ff131c96a1fb
Create Date: 2022-08-02 19:38:52.293526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '528666218b3a'
down_revision = 'ff131c96a1fb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('status', sa.Integer(), server_default='0', nullable=False),
    sa.Column('time_added', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'file_name', name='user_file_uc')
    )
    op.create_table('diff_checker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file1', sa.Integer(), nullable=False),
    sa.Column('file2', sa.Integer(), nullable=False),
    sa.Column('time_requested', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('diff_match', sa.Integer(), nullable=True),
    sa.Column('highlighted_file1', sa.Integer(), nullable=True),
    sa.Column('highlighted_file2', sa.Integer(), nullable=True),
    sa.Column('time_completed', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['file1'], ['files.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['file2'], ['files.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['highlighted_file1'], ['files.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['highlighted_file2'], ['files.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('highlight_duplicates2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file', sa.Integer(), nullable=False),
    sa.Column('time_requested', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('duplicate_rows', sa.Integer(), nullable=True),
    sa.Column('highlighted_file', sa.Integer(), nullable=True),
    sa.Column('analytics_file', sa.Integer(), nullable=True),
    sa.Column('time_completed', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['analytics_file'], ['files.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['file'], ['files.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['highlighted_file'], ['files.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('remove_duplicates2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file', sa.Integer(), nullable=False),
    sa.Column('time_requested', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('duplicate_rows', sa.Integer(), nullable=True),
    sa.Column('without_duplicates_file', sa.Integer(), nullable=True),
    sa.Column('duplicates_file', sa.Integer(), nullable=True),
    sa.Column('time_completed', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['duplicates_file'], ['files.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['file'], ['files.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['without_duplicates_file'], ['files.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('remove_duplicates2')
    op.drop_table('highlight_duplicates2')
    op.drop_table('diff_checker')
    op.drop_table('files')
    # ### end Alembic commands ###
