"""updated server_default of status column of files table

Revision ID: 587acede6aef
Revises: 34d4c273c2c2
Create Date: 2022-08-03 08:35:06.299236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '587acede6aef'
down_revision = '34d4c273c2c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
