"""added highlight_duplicates and remove_duplicates tables

Revision ID: ca8b616dbdb3
Revises: d62297a41351
Create Date: 2022-08-05 15:48:57.629623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca8b616dbdb3'
down_revision = 'd62297a41351'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('highlight_duplicates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file', sa.Integer(), nullable=False),
    sa.Column('unique_columns', sa.String(), nullable=False),
    sa.Column('time_requested', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('duplicate_rows', sa.Integer(), nullable=True),
    sa.Column('highlighted_file', sa.Integer(), nullable=True),
    sa.Column('time_completed', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['file'], ['files.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['highlighted_file'], ['files.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('remove_duplicates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file', sa.Integer(), nullable=False),
    sa.Column('unique_columns', sa.String(), nullable=False),
    sa.Column('time_requested', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('duplicate_rows', sa.Integer(), nullable=True),
    sa.Column('without_duplicates_file', sa.Integer(), nullable=True),
    sa.Column('time_completed', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['file'], ['files.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['without_duplicates_file'], ['files.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('remove_duplicates')
    op.drop_table('highlight_duplicates')
    # ### end Alembic commands ###
