"""changed diff_match column to mismatch_found in diff_checker table

Revision ID: d62297a41351
Revises: 125fd5ad4048
Create Date: 2022-08-03 13:06:17.255653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd62297a41351'
down_revision = '125fd5ad4048'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diff_checker', sa.Column('mismatch_found', sa.Integer(), nullable=True))
    op.drop_column('diff_checker', 'diff_match')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diff_checker', sa.Column('diff_match', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('diff_checker', 'mismatch_found')
    # ### end Alembic commands ###
