"""added search_highlght and search_replace endpoints

Revision ID: e8d473e530ad
Revises: ca8b616dbdb3
Create Date: 2022-08-08 07:36:44.005126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8d473e530ad'
down_revision = 'ca8b616dbdb3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_and_highlight',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file', sa.Integer(), nullable=False),
    sa.Column('search_keyword', sa.String(), nullable=False),
    sa.Column('time_requested', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('num_match', sa.Integer(), nullable=True),
    sa.Column('highlighted_file', sa.Integer(), nullable=True),
    sa.Column('time_completed', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['file'], ['files.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['highlighted_file'], ['files.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('search_and_replace',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file', sa.Integer(), nullable=False),
    sa.Column('search_keyword', sa.String(), nullable=False),
    sa.Column('replace_with', sa.String(), nullable=False),
    sa.Column('time_requested', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('num_match', sa.Integer(), nullable=True),
    sa.Column('replaced_file', sa.Integer(), nullable=True),
    sa.Column('time_completed', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['file'], ['files.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['replaced_file'], ['files.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('search_and_replace')
    op.drop_table('search_and_highlight')
    # ### end Alembic commands ###
