"""Added default value to status column of files table

Revision ID: f364befd5582
Revises: 528666218b3a
Create Date: 2022-08-03 08:12:27.936186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f364befd5582'
down_revision = '528666218b3a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
